#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

lint-staged
lint-staged
lint-staged
yarn lint-staged
npm lint-staged
npm lint-staged
npx lint-staged
npx lint-staged
npm lint-staged
npm run pre-commit
lint-staged
npm lint-staged
